const employeeTypes = {
    ADD_EMPLOYEE_PERSONAL_DETAILS:"ADD_EMPLOYEE_PERSONAL_DETAILS",
    ADD_EMPLOYEE_EDUCATIONAL_DETAILS:" ADD_EMPLOYEE_EDUCATIONAL_DETAILS",
    ADD_EMPLOYEE_ASSETS_DETAILS:"ADD_EMPLOYEE_ASSETS_DETAILS",
    ADD_EMPLOYEE_WORK_EXPERIENCE:"ADD_EMPLOYEE_WORK_EXPERIENCE"
  

}

export default employeeTypes